sudo: required
services:
  - docker

before_install:
  - docker build -t alexadresantos/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexadresantos/docker-react npm run test

language: generic